[package]
name = "gestures"
version = "0.5.0"
edition = "2021"
license = "MIT"
description = "Libinput based touchpad gestures program"
repository = "https://github.com/ferstar/gestures"
keywords = ["touchpad", "gestures", "libinput", "multitouch", "linux"]

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
input = "0.8.1"
libc = "0.2"
nix = {version = "0.26.2", features = ["poll"]}
regex = "1.7"
log = "0.4.17"
env_logger = "0.10.0"
miette = { version = "5.5.0", features = ["fancy"] }
knuffel = "3.0.0"
libxdo = "0.6.0"
timer = "0.2.0"
chrono = "0.4.23"
