name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
     - 'src/**'
     - 'Cargo.toml'
     - '.github/workflows/rust.yml'
  pull_request:
    branches: [ "main" ]
    paths:
     - 'src/**'
     - 'Cargo.toml'
     - '.github/workflows/rust.yml'

env:
  CARGO_TERM_COLOR: always
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Setup
      run: sudo apt-get update && sudo apt-get install -y libudev1 libudev-dev libinput-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
